name: Jawad Nassar
title: Jawad Nassar
tagline: I write about code, tools, and breaking things on purpose.
description: InfoSec, Engineering Management and Digital Privacy.
url: https://jawad.ca
baseurl: ""

author: Jawad Nassar
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope:
      path: ""           # Applies to all files
      type: "posts"      # Applies only to posts in _posts/
    values:
      layout: post
      categories: ["Uncategorized"]
