name: Jawad Nassar
title: Jawad Nassar
tagline: I write about code, tools, and breaking things on purpose.
description: InfoSec, Engineering Management and Digital Privacy.
url: https://jawad.ca
baseurl: ""

author: Jawad Nassar
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
